---
version: "3.8"
services:
  app:
    container_name: transit-dashboard
    build: 
      context: ./
      args:
        - GIT_REVISION
    ports:
      - 8008:8000
    volumes:
      - cache:/db

volumes:
  cache:
