// DO NOT EDIT. This file is generated by Fresh.
// This file SHOULD be checked into source version control.
// This file is automatically updated during development when running `dev.ts`.

import * as $0 from "./routes/_404.tsx";
import * as $1 from "./routes/_app.tsx";
import * as $2 from "./routes/_layout.tsx";
import * as $3 from "./routes/index.tsx";
import * as $4 from "./routes/routes.tsx";
import * as $5 from "./routes/stops.tsx";
import * as $$0 from "./islands/Clock.tsx";
import * as $$1 from "./islands/Locator.tsx";
import * as $$2 from "./islands/Slider.tsx";
import * as $$3 from "./islands/Toggle.tsx";

const manifest = {
  routes: {
    "./routes/_404.tsx": $0,
    "./routes/_app.tsx": $1,
    "./routes/_layout.tsx": $2,
    "./routes/index.tsx": $3,
    "./routes/routes.tsx": $4,
    "./routes/stops.tsx": $5,
  },
  islands: {
    "./islands/Clock.tsx": $$0,
    "./islands/Locator.tsx": $$1,
    "./islands/Slider.tsx": $$2,
    "./islands/Toggle.tsx": $$3,
  },
  baseUrl: import.meta.url,
};

export default manifest;
