# esbuild binary downloads for the Fresh build
[esbuild-version]
src.cmd = "grep -Eo -m1 'esbuild@v([0-9]+\\.?){3}' deno.lock"
src.prefix = "esbuild@v"

[esbuild-aarch64-linux]
src.combiner = "grep -Eo -m1 'esbuild@v([0-9]+\\.?){3}' deno.lock"
src.prefix = "esbuild@v"
fetch.tarball = "https://registry.npmjs.org/@esbuild/linux-arm64/-/linux-arm64-$ver.tgz"

[esbuild-x86_64-linux]
src.cmd = "grep -Eo -m1 'esbuild@v([0-9]+\\.?){3}' deno.lock"
src.prefix = "esbuild@v"
fetch.tarball = "https://registry.npmjs.org/@esbuild/linux-x64/-/linux-x64-$ver.tgz"

[esbuild-aarch64-darwin]
src.cmd = "grep -Eo -m1 'esbuild@v([0-9]+\\.?){3}' deno.lock"
src.prefix = "esbuild@v"
fetch.tarball = "https://registry.npmjs.org/@esbuild/darwin-arm64/-/darwin-arm64-$ver.tgz"

[esbuild-x86_64-darwin]
src.cmd = "grep -Eo -m1 'esbuild@v([0-9]+\\.?){3}' deno.lock"
src.prefix = "esbuild@v"
fetch.tarball = "https://registry.npmjs.org/@esbuild/darwin-x64/-/darwin-x64-$ver.tgz"
